[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
taskcli = "taskcli.taskcli:main"

[project]
name = "task-treaker-cli"
version = "0.1.1"
description = "Task treaker cli tool"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tabulate>=0.9.0",
]
authors = [{ name = "Jaracomp" }]
[project.urls]
Homepage = "https://github.com/Jaracomp/Task-treaker-CLI"

[tool.uv]
package = true
