[project]
name = "taskcli"
version = "0.1.2"
description = "Task treaker CLI tool"
authors = [{ name = "Jaracomp"}]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tabulate>=0.9.0"
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
taskcli = "taskcli.main:main"

[tool.ruff]
line-length = 120
select = ["I"]
fix = true
